from django import forms

STATE_CHOICES = [('AL','AL'),
('AK','AK'),
('AZ','AZ'),
('AR','AR'),
('CA','CA'),
('CO','CO'),
('CT','CT'),
('DE','DE'),
('DC','DC'),
('FL','FL'),
('GA','GA'),
('HI','HI'),
('ID','ID'),
('IL','IL'),
('IN','IN'),
('IA','IA'),
('KS','KS'),
('KY','KY'),
('LA','LA'),
('ME','ME'),
('MD','MD'),
('MA','MA'),
('MI','MI'),
('MN','MN'),
('MS','MS'),
('MO','MO'),
('MT','MT'),
('NE','NE'),
('NV','NV'),
('NH','NH'),
('NJ','NJ'),
('NM','NM'),
('NY','NY'),
('NC','NC'),
('ND','ND'),
('OH','OH'),
('OK','OK'),
('OR','OR'),
('PA','PA'),
('PR','PR'),
('RI','RI'),
('SC','SC'),
('SD','SD'),
('TN','TN'),
('TX','TX'),
('UT','UT'),
('VT','VT'),
('VA','VA'),
('WA','WA'),
('WV','WV'),
('WI','WI'),
('WY','WY')]

class AddressForm(forms.Form):
    street = forms.CharField(required=True)
    city = forms.CharField(required=True)
    state = forms.ChoiceField(required=True,choices=STATE_CHOICES)
    zip = forms.IntegerField(min_value=0,max_value=100000)